CREATE SEQUENCE Angajat_id
    START WITH 1000
    INCREMENT BY 1;
    
CREATE SEQUENCE Magazin_id
    START WITH 2000
    INCREMENT BY 1;
    
CREATE SEQUENCE Locatie_id
    START WITH 3000
    INCREMENT BY 1;
    
CREATE SEQUENCE Comanda_id
    START WITH 4000
    INCREMENT BY 1;

CREATE SEQUENCE Client_id
    START WITH 5000
    INCREMENT BY 1;
    
CREATE SEQUENCE Produs_id
    START WITH 6000
    INCREMENT BY 1;